### ISSUE TITLE
Temporary anka-base-XXXXXXXXX VM should be deleted after cloning to vm_name

### ISSUE THREAD

**Issue by jeremiahsnapp** [veertuinc/packer-builder-veertu-anka#13]
I think the temporary anka-base-XXXXXXXXX VM should be deleted after cloning to the destination vm_name VM

**Comment by catflight** [comment]
The base VM could be used as _source_vm_name_ for another build operations. From perspective of efficiency of disk space usage, it's recommended to use same base VM (with guest operating system and common stuff preinstalled) for different destination VMs.

**Comment by tduffield** [comment]
It should at least be optional. We have no control over the name and you're appending a random sequence at the end of the name. Looking at the list of images is meaningless because you have no context as to which image is associated with what source. This is especially true in an unattended CI system.
